baseURL = 'https://khairuliman.com/'
languageCode = 'en-us'
title = 'Khairul Iman'

theme = 'gokarna'

# Automatically generate robots.txt
enableRobotsTXT = true

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"

    url = "/posts/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Posts"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    identifier = "github"
    url = "https://github.com/namiwa"
    weight = 2
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"

[params]
  togglePreviousAndNextButtons = "true"
  description = 'Hi 👋! Currently software engineer based in Singapore, in the midst of learning compilers in C & Java, and OpenGL in C++ :D'
