[package]
name = "rust-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { version = "0.4.3", features = ["csr", "nightly"] }
pulldown-cmark = "0.9.3"
wasm-pack = "0.12.1"
